server:
  port: 8080

springdoc:
  datasource:
    url: jdbc:postgresql://localhost:5432/local_db
    username: local_user
    password: local_password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  swagger-ui:
    path: /swagger-ui.html

logging:
  level:
    org:
    springframework:
     security: DEBUG