name: CI Develop

on:
  pull_request:
    branches:
      - main
      - develop

jobs:
  check-application:
    strategy:
      matrix:
        ubuntu: [ 'ubuntu-latest' ]
        java: [ '17' ]
    runs-on: ${{ matrix.ubuntu }}
    steps:
      - name: Checkout codigo
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: ${{ matrix.java }}

      - name: Setup Maven
        run: |
            sudo apt-get install -y maven

      - name: Install Dependencies
        run: mvn clean install -DskipTests

      - name: Run Tests
        run: mvn test
